"""
MedRax Inference Service
=========================
Handles the end-to-end inference pipeline: prompt construction, model
invocation, and response decoding.

This module sits between the UI layer and the ModelManager.  It accepts
a PIL Image + user query, formats them into MedGemma's multimodal chat
template, runs generation, and returns the decoded text.

Architecture:
  - Uses MedGemma's chat template format (list of messages with roles)
  - Supports configurable system prompts per analysis type
  - All generation parameters come from ``config.settings``
  - Thread-safe via the underlying ModelManager singleton

Usage:
    from services.inference import InferenceService

    service = InferenceService()
    result = service.analyze(image, "Describe any abnormalities in this chest X-ray.")
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

import torch
from PIL import Image

from config import settings
from services.model_manager import ModelManager
from utils.logger import get_logger

logger = get_logger(__name__)


class AnalysisType(str, Enum):
    """Predefined analysis modes with specialized system prompts.

    Each mode tailors MedGemma's behavior toward a specific clinical task.
    """

    GENERAL = "general"
    FINDINGS = "findings"
    DIFFERENTIAL = "differential"
    REPORT = "report"
    COMPARISON = "comparison"
    PATIENT_FRIENDLY = "patient_friendly"


# ---------------------------------------------------------------------------
# System prompts — each guides MedGemma toward a specific output style
# ---------------------------------------------------------------------------
_SYSTEM_PROMPTS: dict[AnalysisType, str] = {
    AnalysisType.GENERAL: (
        "You are an expert medical imaging AI assistant. Analyze the provided "
        "medical image carefully and provide a thorough, structured analysis. "
        "Include observations about anatomy, any abnormalities, and relevant "
        "clinical correlations. Be precise and use standard medical terminology."
    ),
    AnalysisType.FINDINGS: (
        "You are a radiologist assistant. Examine the provided medical image "
        "and list all findings in a structured format. For each finding, "
        "describe: (1) Location, (2) Appearance, (3) Size if estimable, "
        "(4) Clinical significance. Organize findings by severity."
    ),
    AnalysisType.DIFFERENTIAL: (
        "You are a diagnostic imaging specialist. Based on the provided "
        "medical image, generate a differential diagnosis. List the most "
        "likely diagnoses in order of probability, providing supporting "
        "evidence from the image for each. Include relevant clinical "
        "considerations and suggest any additional imaging or tests."
    ),
    AnalysisType.REPORT: (
        "You are a radiologist generating a structured medical report. "
        "Analyze the provided image and produce a formal radiology report "
        "with the following sections: TECHNIQUE, COMPARISON, FINDINGS, "
        "and IMPRESSION. Use professional medical language appropriate "
        "for a clinical report."
    ),
    AnalysisType.COMPARISON: (
        "You are a radiologist assistant specialized in comparative analysis. "
        "Describe the findings in the provided medical image in detail. "
        "Note any features that would be important to compare with prior "
        "imaging studies, including interval changes that should be tracked."
    ),
    AnalysisType.PATIENT_FRIENDLY: (
        "You are a compassionate medical AI assistant explaining imaging "
        "results to a patient. Analyze the provided medical image and "
        "explain the findings in simple, non-technical language. Avoid "
        "jargon, be reassuring where appropriate, and suggest that the "
        "patient discuss the results with their healthcare provider."
    ),
}

# Medical disclaimer appended to all outputs
_DISCLAIMER = (
    "\n\n---\n"
    "⚠️ **Disclaimer**: This analysis is generated by an AI model "
    "(MedGemma) and is intended for educational and research purposes only. "
    "It is NOT a substitute for professional medical advice, diagnosis, or "
    "treatment. Always consult a qualified healthcare professional for "
    "clinical decisions."
)


class InferenceService:
    """Orchestrates the inference pipeline for medical image analysis.

    This service formats inputs into MedGemma's expected chat template,
    runs generation with configured parameters, and decodes the output.
    """

    def __init__(self, model_manager: Optional[ModelManager] = None) -> None:
        """Initialize the inference service.

        Args:
            model_manager: An existing ModelManager instance.
                If ``None``, the singleton is used.
        """
        self._manager = model_manager or ModelManager()

    def analyze(
        self,
        image: Image.Image,
        query: str,
        analysis_type: AnalysisType = AnalysisType.GENERAL,
        add_disclaimer: bool = True,
    ) -> str:
        """Run a full analysis on a medical image.

        Args:
            image: A preprocessed PIL Image in RGB mode.
            query: The user's question or instruction about the image.
            analysis_type: The type of analysis to perform.
            add_disclaimer: Whether to append the medical disclaimer.

        Returns:
            The model's text response, optionally with disclaimer.

        Raises:
            RuntimeError: If the model is not loaded or inference fails.
        """
        logger.info(
            "Starting %s analysis (query length: %d chars)",
            analysis_type.value,
            len(query),
        )

        # Build the chat messages
        messages = self._build_messages(image, query, analysis_type)

        # Run generation
        raw_output = self._generate(messages)

        # Post-process
        response = self._post_process(raw_output)

        if add_disclaimer:
            response += _DISCLAIMER

        logger.info(
            "Analysis complete (response length: %d chars)", len(response)
        )
        return response

    def text_only_query(self, query: str) -> str:
        """Run a text-only query without an image (e.g., medical questions).

        Args:
            query: The user's medical question.

        Returns:
            The model's text response with disclaimer.
        """
        logger.info("Text-only query (length: %d chars)", len(query))

        messages = [
            {
                "role": "system",
                "content": [{"type": "text", "text": _SYSTEM_PROMPTS[AnalysisType.GENERAL]}],
            },
            {
                "role": "user",
                "content": [{"type": "text", "text": query}],
            },
        ]

        raw_output = self._generate(messages)
        response = self._post_process(raw_output)
        response += _DISCLAIMER
        return response

    # ── Private Helpers ───────────────────────────────────────────────────

    def _build_messages(
        self,
        image: Image.Image,
        query: str,
        analysis_type: AnalysisType,
    ) -> list[dict]:
        """Build the multimodal chat message list for MedGemma.

        MedGemma expects messages in a specific format where each content
        item has a ``type`` key (``"text"`` or ``"image"``).
        """
        system_prompt = _SYSTEM_PROMPTS.get(
            analysis_type, _SYSTEM_PROMPTS[AnalysisType.GENERAL]
        )

        messages = [
            {
                "role": "system",
                "content": [{"type": "text", "text": system_prompt}],
            },
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": query},
                ],
            },
        ]
        return messages

    def _generate(self, messages: list[dict]) -> str:
        """Run model generation on the prepared messages.

        Uses ``processor.apply_chat_template()`` to tokenize and format
        the inputs, then calls ``model.generate()`` with configured
        generation parameters.
        """
        model = self._manager.get_model()
        processor = self._manager.get_processor()

        # Apply chat template → tokenize → move to device
        inputs = processor.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            return_tensors="pt",
        )

        # Move tensors to model's device
        model_device = next(model.parameters()).device
        inputs = {
            key: val.to(model_device) if isinstance(val, torch.Tensor) else val
            for key, val in inputs.items()
        }

        # Calculate input length for output extraction
        input_len = inputs["input_ids"].shape[-1]

        # Run generation
        logger.debug("Running generation (max_new_tokens=%d)...", settings.max_new_tokens)
        with torch.inference_mode():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=settings.max_new_tokens,
                temperature=settings.temperature if settings.do_sample else None,
                top_p=settings.top_p if settings.do_sample else None,
                do_sample=settings.do_sample,
            )

        # Decode only the generated tokens (skip the input)
        generated_ids = output_ids[0][input_len:]
        decoded = processor.decode(generated_ids, skip_special_tokens=True)
        return decoded

    @staticmethod
    def _post_process(text: str) -> str:
        """Clean up the model's raw output.

        Removes leading/trailing whitespace and any residual special tokens
        or formatting artifacts.
        """
        # Strip whitespace
        text = text.strip()

        # Remove any residual model artifacts
        # (MedGemma is generally clean, but this is defensive)
        unwanted_prefixes = ["assistant\n", "Assistant:\n", "Response:\n"]
        for prefix in unwanted_prefixes:
            if text.startswith(prefix):
                text = text[len(prefix):].strip()

        return text
