"""
MedRax Report Generator
=========================
Transforms MedGemma's raw AI output into structured, exportable medical reports.

This module handles:
  - Structuring raw text into report sections (Findings, Impressions, etc.)
  - Adding metadata (timestamp, model version, disclaimers)
  - Exporting reports as plain text, Markdown, and PDF
  - Saving reports to the local filesystem and optionally to Google Cloud Storage
  - Generating unique report identifiers for tracking

Usage:
    from models.report_generator import ReportGenerator

    generator = ReportGenerator()
    report = generator.create_report(
        analysis_text="...",
        query="Describe this X-ray",
        analysis_type="general",
        image_filename="chest_xray.dcm",
    )
    # Access structured data
    print(report.markdown)

    # Export as PDF
    generator.export_pdf(report)
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from config import settings
from utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class MedicalReport:
    """Structured representation of a medical image analysis report.

    This object holds all report data in a format-agnostic way and
    provides properties for rendering as plain text, Markdown, or
    supplying data for PDF generation.
    """

    # ── Core Content ──────────────────────────────────────────────────────
    report_id: str = ""
    analysis_text: str = ""
    query: str = ""
    analysis_type: str = "general"

    # ── Metadata ──────────────────────────────────────────────────────────
    timestamp: str = ""
    model_id: str = ""
    image_filename: str = ""

    # ── Paths (populated after saving) ────────────────────────────────────
    saved_path: Optional[Path] = None

    # ── Internal ──────────────────────────────────────────────────────────
    _sections: dict[str, str] = field(default_factory=dict, repr=False)

    @property
    def title(self) -> str:
        """Generate a descriptive report title."""
        type_labels = {
            "general": "General Medical Image Analysis",
            "findings": "Radiological Findings Report",
            "differential": "Differential Diagnosis Report",
            "report": "Formal Radiology Report",
            "comparison": "Comparative Analysis Report",
            "patient_friendly": "Patient Summary Report",
        }
        return type_labels.get(self.analysis_type, "Medical Image Analysis Report")

    @property
    def sections(self) -> dict[str, str]:
        """Parsed sections of the report."""
        return self._sections

    @property
    def markdown(self) -> str:
        """Render the full report as Markdown."""
        lines = [
            f"# {self.title}",
            "",
            "---",
            "",
            "## Report Information",
            "",
            f"| Field | Value |",
            f"|---|---|",
            f"| **Report ID** | `{self.report_id}` |",
            f"| **Date** | {self.timestamp} |",
            f"| **Model** | {self.model_id} |",
            f"| **Image** | {self.image_filename or 'N/A'} |",
            f"| **Analysis Type** | {self.analysis_type.replace('_', ' ').title()} |",
            "",
            "---",
            "",
            "## Clinical Query",
            "",
            f"> {self.query}",
            "",
            "---",
            "",
        ]

        # Add parsed sections or the full analysis
        if self._sections:
            for section_title, section_content in self._sections.items():
                lines.append(f"## {section_title}")
                lines.append("")
                lines.append(section_content)
                lines.append("")
        else:
            lines.append("## Analysis")
            lines.append("")
            lines.append(self.analysis_text)
            lines.append("")

        # Disclaimer
        lines.extend([
            "---",
            "",
            "> ⚠️ **Disclaimer**: This report is generated by an AI model "
            "and is intended for educational and research purposes only. "
            "It is NOT a substitute for professional medical advice, "
            "diagnosis, or treatment. Always consult a qualified healthcare "
            "professional for clinical decisions.",
        ])

        return "\n".join(lines)

    @property
    def plain_text(self) -> str:
        """Render the report as plain text (no Markdown formatting)."""
        lines = [
            self.title.upper(),
            "=" * len(self.title),
            "",
            f"Report ID:     {self.report_id}",
            f"Date:          {self.timestamp}",
            f"Model:         {self.model_id}",
            f"Image:         {self.image_filename or 'N/A'}",
            f"Analysis Type: {self.analysis_type.replace('_', ' ').title()}",
            "",
            "-" * 60,
            "",
            "CLINICAL QUERY:",
            self.query,
            "",
            "-" * 60,
            "",
        ]

        if self._sections:
            for section_title, section_content in self._sections.items():
                lines.append(section_title.upper())
                lines.append("-" * len(section_title))
                lines.append(section_content)
                lines.append("")
        else:
            lines.append("ANALYSIS")
            lines.append("-" * 8)
            lines.append(self.analysis_text)
            lines.append("")

        lines.extend([
            "-" * 60,
            "",
            "DISCLAIMER: This report is generated by an AI model and is "
            "intended for educational and research purposes only.",
        ])

        return "\n".join(lines)


class ReportGenerator:
    """Generates structured medical reports from MedGemma's raw output.

    This class handles:
      - Parsing raw AI text into logical sections
      - Creating ``MedicalReport`` objects with metadata
      - Saving reports to disk (Markdown and PDF)
      - Optional upload to Google Cloud Storage
    """

    def __init__(self) -> None:
        self._report_dir = settings.report_dir

    def create_report(
        self,
        analysis_text: str,
        query: str,
        analysis_type: str = "general",
        image_filename: str = "",
    ) -> MedicalReport:
        """Create a structured report from raw analysis text.

        Args:
            analysis_text: The raw text output from MedGemma.
            query: The original user query.
            analysis_type: The type of analysis performed.
            image_filename: Name of the analyzed image file.

        Returns:
            A populated ``MedicalReport`` instance.
        """
        report = MedicalReport(
            report_id=self._generate_id(),
            analysis_text=analysis_text,
            query=query,
            analysis_type=analysis_type,
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            model_id=settings.model_id,
            image_filename=image_filename,
        )

        # Parse sections from the raw text
        report._sections = self._parse_sections(analysis_text)

        logger.info("Report created: %s", report.report_id)
        return report

    def save_report(self, report: MedicalReport) -> Path:
        """Save a report as a Markdown file to the reports directory.

        Args:
            report: The report to save.

        Returns:
            The path to the saved file.
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = f"report_{timestamp}_{report.report_id[:8]}.md"
        file_path = self._report_dir / filename

        file_path.write_text(report.markdown, encoding="utf-8")
        report.saved_path = file_path

        logger.info("Report saved: %s", file_path)
        return file_path

    def export_pdf(self, report: MedicalReport) -> Path:
        """Export a report as a PDF file.

        Args:
            report: The report to export.

        Returns:
            The path to the generated PDF.
        """
        try:
            from fpdf import FPDF
        except ImportError:
            logger.error("fpdf2 is not installed. Run: pip install fpdf2")
            raise ImportError(
                "fpdf2 is required for PDF export. Install with: pip install fpdf2"
            )

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, report.title, new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(5)

        # Metadata
        pdf.set_font("Helvetica", "", 9)
        meta_lines = [
            f"Report ID: {report.report_id}",
            f"Date: {report.timestamp}",
            f"Model: {report.model_id}",
            f"Image: {report.image_filename or 'N/A'}",
            f"Analysis Type: {report.analysis_type.replace('_', ' ').title()}",
        ]
        for line in meta_lines:
            pdf.cell(0, 5, line, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)

        # Separator
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        # Clinical Query
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Clinical Query", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 10)
        pdf.multi_cell(0, 6, report.query)
        pdf.ln(5)

        # Sections
        if report.sections:
            for section_title, section_content in report.sections.items():
                pdf.set_font("Helvetica", "B", 12)
                pdf.cell(0, 8, section_title, new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 10)
                # Handle encoding — fpdf2 supports UTF-8 by default
                safe_content = section_content.encode("latin-1", "replace").decode("latin-1")
                pdf.multi_cell(0, 6, safe_content)
                pdf.ln(3)
        else:
            pdf.set_font("Helvetica", "B", 12)
            pdf.cell(0, 8, "Analysis", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            safe_text = report.analysis_text.encode("latin-1", "replace").decode("latin-1")
            pdf.multi_cell(0, 6, safe_text)

        # Disclaimer
        pdf.ln(10)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(128, 128, 128)
        pdf.multi_cell(
            0,
            4,
            "DISCLAIMER: This report is generated by an AI model and is "
            "intended for educational and research purposes only. It is NOT "
            "a substitute for professional medical advice, diagnosis, or "
            "treatment. Always consult a qualified healthcare professional "
            "for clinical decisions.",
        )

        # Save
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = f"report_{timestamp}_{report.report_id[:8]}.pdf"
        file_path = self._report_dir / filename

        pdf.output(str(file_path))
        logger.info("PDF report exported: %s", file_path)
        return file_path

    def save_to_gcs(self, report: MedicalReport) -> Optional[str]:
        """Upload a saved report to Google Cloud Storage.

        Args:
            report: The report to upload (must be saved locally first).

        Returns:
            The GCS URI of the uploaded file, or ``None`` if GCS is not enabled.
        """
        if not settings.gcs_enabled:
            logger.debug("GCS not enabled — skipping cloud upload.")
            return None

        if report.saved_path is None or not report.saved_path.exists():
            logger.warning("Report has not been saved locally. Call save_report() first.")
            return None

        try:
            from google.cloud import storage as gcs

            client = gcs.Client(project=settings.gcp_project_id)
            bucket = client.bucket(settings.gcs_bucket_name)
            blob_name = f"reports/{report.saved_path.name}"
            blob = bucket.blob(blob_name)

            blob.upload_from_filename(str(report.saved_path))
            gcs_uri = f"gs://{settings.gcs_bucket_name}/{blob_name}"

            logger.info("Report uploaded to GCS: %s", gcs_uri)
            return gcs_uri

        except ImportError:
            logger.error("google-cloud-storage not installed.")
            return None
        except Exception as exc:
            logger.error("Failed to upload report to GCS: %s", exc)
            return None

    # ── Private Helpers ───────────────────────────────────────────────────

    def _parse_sections(self, text: str) -> dict[str, str]:
        """Parse raw analysis text into named sections.

        MedGemma's output often naturally contains headers like
        "FINDINGS:", "IMPRESSION:", etc.  This method detects these
        and splits the text accordingly.

        If no recognizable headers are found, the entire text is
        returned as a single "Analysis" section.
        """
        # Common medical report section headers (case-insensitive)
        known_headers = [
            "TECHNIQUE",
            "COMPARISON",
            "FINDINGS",
            "IMPRESSION",
            "IMPRESSIONS",
            "RECOMMENDATION",
            "RECOMMENDATIONS",
            "CONCLUSION",
            "CONCLUSIONS",
            "DIFFERENTIAL DIAGNOSIS",
            "DIFFERENTIAL",
            "CLINICAL HISTORY",
            "HISTORY",
            "INDICATION",
            "OBSERVATION",
            "OBSERVATIONS",
            "SUMMARY",
            "ASSESSMENT",
            "PLAN",
            "DESCRIPTION",
        ]

        sections: dict[str, str] = {}
        current_header = None
        current_content: list[str] = []

        for line in text.split("\n"):
            stripped = line.strip()

            # Check if this line is a section header
            is_header = False
            for header in known_headers:
                # Match patterns like "FINDINGS:", "**FINDINGS**", "## FINDINGS"
                clean = stripped.lstrip("#* ").rstrip(":* ")
                if clean.upper() == header:
                    # Save previous section
                    if current_header is not None:
                        sections[current_header] = "\n".join(current_content).strip()
                    elif current_content:
                        # Content before any header
                        preamble = "\n".join(current_content).strip()
                        if preamble:
                            sections["Overview"] = preamble

                    current_header = header.title()
                    current_content = []
                    is_header = True
                    break

            if not is_header:
                current_content.append(line)

        # Save the last section
        if current_header is not None:
            sections[current_header] = "\n".join(current_content).strip()
        elif current_content:
            text_block = "\n".join(current_content).strip()
            if text_block:
                sections["Analysis"] = text_block

        # If no sections were parsed, return the raw text as a single section
        if not sections:
            sections["Analysis"] = text.strip()

        logger.debug("Parsed %d sections: %s", len(sections), list(sections.keys()))
        return sections

    @staticmethod
    def _generate_id() -> str:
        """Generate a unique report identifier."""
        return str(uuid.uuid4())
